version: '3.3'

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=christian70401@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    restart: always

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    networks:
      - web
    restart: always

  prefect-ui:
    build:
      context: ./prefect-ui
      dockerfile: Dockerfile
    command: ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prefect.rule=Host(`workflows.mlworkshop.space`)"
      - "traefik.http.routers.prefect.entrypoints=websecure"
      - "traefik.http.routers.prefect.tls.certresolver=myresolver"
      - "traefik.docker.network=web"
    networks:
      - web
    environment:
      - PREFECT_API_URL=http://workflows.mlworkshop.space:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "4200:4200"
    restart: always

  prefect-worker1:
    image: prefecthq/prefect:3-latest
    command: ["prefect", "worker", "start", "--pool", "local-process"]
    environment:
      - PREFECT_API_URL=http://workflows.mlworkshop.space:4200/api
    networks:
      - web
    restart: always


networks:
  web:
    driver: bridge

volumes:
  letsencrypt:

  postgres_data:
